services:
  backend:
    image: node:20-alpine
    build: 
      context: .
      target: development
    volumes:
        - ./:/app
        - /app/node_modules
    ports:
      - "5000:5000"
    command: sh -c "npm run dev:docker"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"